[features]
seeds = false
skip-lint = false
[programs.localnet]
virt = "VRTEittKzMw7RxcmwAvk9WEQwjrceHawEM3fpzg9LUc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/austin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --grep ab"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/mpl_token_metadata.so"